[build]
  command = "bundle exec jekyll build" # Or your specific build command
  publish = "build/wwwroot"

[build.environment]
  RUBY_VERSION = "2.7.2"
  NODE_VERSION = "16"  # Optional: specify the Node.js version if needed
  DOTNET_ROOT = "/opt/buildhome/.dotnet"
  PATH = "/opt/buildhome/.dotnet:$PATH"

[[plugins]]
  package = "netlify-plugin-dotnetcore"
  inputs = { version = "7.0.x" }  # Specify your .NET version here
